version: 2
jobs:
  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-11:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node-12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - run: yarn run build
      - run: npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - test-node-10: {}
      - test-node-11: {}
      - test-node-12: {}
      - deploy:
          requires:
            - test-node-10
            - test-node-11
            - test-node-12
          filters:
            branches:
              only: master
